version: '3.7'


services:
  app:
    build: ./
    container_name: app
    command: ./wait-for-postgres.sh postgres ./app
    environment:
      HTTP_SERVER_ADDRESS: 0.0.0.0
      HTTP_SERVER_PORT: 8000
      HTTP_SERVER_TIMEOUT: 10s
      HTTP_SERVER_IDLE_TIMEOUT: 30s
      POSTGRES_HOST: 192.168.200.103
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: referrals
      POSTGRES_SSL_MODE: disable
    depends_on:
      - postgres
    networks:
      my_network:
        ipv4_address: 192.168.200.104

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: referrals
      POSTGRES_SSL_MODE: disable
    networks:
      my_network:
        ipv4_address: 192.168.200.103

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24
