version: '3.8'


services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: referrals
      POSTGRES_SSL_MODE: disable
    networks:
      portfolio_net:
        ipv4_address: 192.168.56.103

  app:
    build: ./
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - HTTP_SERVER_ADDRESS=127.0.0.1
      - HTTP_SERVER_PORT=8080
      - HTTP_SERVER_TIMEOUT=10s
      - HTTP_SERVER_IDLE_TIMEOUT=30s
      - POSTGRES_HOST=192.168.56.2
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=referrals
      - POSTGRES_SSL_MODE=disable


volumes:
  mysqldb:

networks:
  portfolio_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.56.0/24