version: '3.8'


services:
  mysql:
    image: postgres:latest
    container_name: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: referrals
      POSTGRES_SSL_MODE: disable
    networks:
      portfolio_net:
        ipv4_address: 192.168.56.103

volumes:
  mysqldb:

networks:
  portfolio_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.56.0/24