version: '3.7'


services:
  app:
    build: ./
    container_name: app
    ports:
      - 8000:8000
    environment:
      HTTP_SERVER_ADDRESS: 0.0.0.0
      HTTP_SERVER_PORT: 8000
      HTTP_SERVER_TIMEOUT: 10s
      HTTP_SERVER_IDLE_TIMEOUT: 30s
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: referrals
      POSTGRES_SSL_MODE: disable
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: referrals
      POSTGRES_SSL_MODE: disable
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s 
      retries: 5